### ISSUE TITLE
Add target for JS

### ISSUE THREAD

**Issue by shalva97** [eygraber/uri-kmp#31]
When I added it to my project I get these errors

```
MySmallProject:jsMain: Could not resolve com.eygraber:uri-kmp:0.0.6.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by eygraber** [comment]
Should be available https://search.maven.org/artifact/com.eygraber/uri-kmp-js/0.0.6/klib

**Comment by shalva97** [comment]
Just tested with a new project and still does not work

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("multiplatform") version "1.7.10"
}

group = "org.example"
version = "1.0-SNAPSHOT"

kotlin {
    js().browser()
    sourceSets {
        val commonMain by getting
    }
}
repositories {
    mavenCentral()
}

dependencies {
//    testImplementation(kotlin("test"))
    commonMainImplementation("com.eygraber:uri-kmp-js:0.0.6")
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
```
I have only changed "jvm" to "multiplatform" and added kotlin {} target. Still shows `untitled1:jsMain: Could not resolve com.eygraber:uri-kmp-js:0.0.6.` :/

**Comment by eygraber** [comment]
Try using `commonMainImplementation("com.eygraber:uri-kmp:0.0.6")`. It should resolve the js artifact for you js target.

**Comment by rocketraman** [comment]
Same issue here:

```
hawkish-bewit:jsMain: Could not resolve com.eygraber:uri-kmp:0.0.6.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

The download appears to have worked but gradle still doesn't resolve it:

```
Download https://repo.maven.apache.org/maven2/com/eygraber/uri-kmp-js/0.0.6/uri-kmp-js-0.0.6.pom, took 89 ms (1.95 kB)
Download https://repo.maven.apache.org/maven2/com/eygraber/uri-kmp-js/0.0.6/uri-kmp-js-0.0.6.module, took 51 ms (2.65 kB)
Download https://repo.maven.apache.org/maven2/com/eygraber/uri-kmp-js/0.0.6/uri-kmp-js-0.0.6.klib, took 53 ms (92.85 kB)
Download https://repo.maven.apache.org/maven2/com/eygraber/uri-kmp-js/0.0.6/uri-kmp-js-0.0.6-sources.jar, took 18 ms (27.59 kB
```

**Comment by rocketraman** [comment]
Even when commenting out the JS target I have build failures:

```
* What went wrong:
Execution failed for task ':compileKotlinMetadata'.
> Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlinMetadata'
   > Could not resolve all files for configuration ':metadataCompileClasspath'.
      > Could not resolve com.eygraber:uri-kmp:0.0.6.
        Required by:
            project :
         > The consumer was configured to find a usage of 'kotlin-api' of a library, preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common'. However we cannot choose between the following variants of com.eygraber:uri-kmp:0.0.6:
             - androidNativeArm32ApiElements-published
             - androidNativeArm64ApiElements-published
             - androidNativeX64ApiElements-published
             - androidNativeX86ApiElements-published
...
```

**Comment by eygraber** [comment]
I'll take a deeper look and see what's going on

**Comment by eygraber** [comment]
Yes, and I apologize I haven't gotten to it yet (busy with work). PRs are accepted 😅

**Comment by eygraber** [comment]
Please test 0.0.7-SNAPSHOT (after https://github.com/eygraber/uri-kmp/actions/runs/2959915859 is done running) and let me know if this is fixed.

**Comment by eygraber** [comment]
Just an FYI, from the next version going forward there won't be any more LEGACY builds for js
